version: 2
updates:
  - package-ecosystem: "npm"
    directories: 
      - "/"
      - "/app"
      - "/cli"
    schedule:
      interval: "weekly"
      timezone: "America/Los_Angeles"
    # Specify labels for npm pull requests
    labels:
      - "♡ care"
      - "t: security"
  
