name: "⎙ Acceptance Feedback"
description: "Reviewing a behavior for formal acceptance and have feedback? Use this form."
title: "Feedback for: [Behavior or Issue #]"
labels: "triage, ♡ care"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        # What is Acceptance Feedback?
        Acceptance feedback is feedback that represents your thoughts around a specific behavior you are reviewing.
        This feedback can represent either:
        1. :bulb: New ideas 
        2. *or* A problem.
        3. *or* Both or Unsure

        For choice (1.) your ideas will be reviewed and each will be drafted into formal :bulb: Ideas for 
        consideration.

        In the case of (2.), it means you have found a problem that should prevent the behavior from being
        accepted and moving forward to production (live) deployment.
        
        In both cases, you should provide as much detail as possible!
  - type: dropdown
    attributes:
      label: Feedback Representing...
      multiple: false
      options:
        - "New Ideas"
        - "A Problem"
        - Both or Unsure
      default: 0
    validations:
      required: true
  - type: input
    attributes:
      label: "Behavior or Issue #"
      value: "#"
      description: "Please provide the Behavior or Issue # this feedback is relevant to.<br />:warning: The '#' symbol must be followed by the number, for example: `#13`"
  - type: dropdown
    attributes:
      label: "Communication & Considerations"
      description: Any special considerations for communication about this issue?
      multiple: false
      options:
        - "None: Use regular communication channels and proceed immediately."
        - "Discussion Hold: I would like to discuss this issue before any work begins."
      default: 0
    validations:
      required: true
  - type: textarea
    attributes:
      label: Feedback
      description: "Describe the details of your feedback. Please include any screenshots to help our team by uploading or pasting them into the editor below."
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > If you are experiencing a :cyclone: Problem, please include the following details (when applicable):
        > 1. The URL in your browser where the problem occurred.    
        > 2. The browser and browser version you are using. [CTRL+click here to find it.](https://www.whatismybrowser.com/)    
        > 3. Attach relevant screenshots of the problem.
        > 4. A description of what you were doing just before the problem occurred.
        > 5. A description of your expected result.
