name: "♡ Care Task - Request a thing to be done."
description: "Define a simple task or to-do for the team to complete."
title: "Requesting something..."
labels: "triage, ♡ care, p: low"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > The **title** of this issue will be processed by the AppKu AI. You may include a brief title to help guide the AI or leave it as-is.
        
        # :heart: Welcome!
        This form is filled out to add a new formal :heart: Care task to the project.    
  - type: dropdown
    id: environments
    attributes:
      label: In which environment(s) do you want this done?
      description: If you're unsure please skip this selection.
      multiple: true
      default: 0
      options:
        - All
        - Production ("Live")
        - Review
        - Staging (AppKu Internal)
  - type: textarea
    attributes:
      label: What is the Task to be Completed?
      description: |
        Please describe the details of your task. Care tasks should be simplistic and generally of one concern, and not something
        that could be better described as a behavior or Care *request*.
      value: 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Any Relevant Samples & Materials?
      description: |
        Are there any relevant sample files or materials that are required or relevant to this task?
      value: _None_
