name: "\U000026AF New Ask"
description: "A plan to improve or enhance a product."
title: "Ask: [Brief Description]"
labels: 
  - "✎ draft"
  - "⚯ ask"
  - "p: low"
assignees: []
body:
  - type: textarea
    id: ask
    attributes:
      label: Ask
      description: |
        **_What is the ask?_**
      value: 
    validations:
      required: true
  - type: textarea
    id: story-changes
    attributes:
      label: Changes to the Story
      description: |
        **_What, Where, Who, & Why?_**
      value: |
        ##### Changes to _What_
        _None_
        ##### Changes to _Where_
        _None_
        ##### Changes to _Who_
        _None_
        ##### Changes to _Why_
        _None_
  - type: textarea
    id: task-list
    attributes:
      label: Ask
      description: |
        **_List the Tasks that would be required._**
      value: |
        - TBD ⚡ X
        - TBD ⚡ X
        - TBD ⚡ X
        - TBD ⚡ X
