name: "☰ New Story"
description: "Add a new product story to this project."
title: "Story: TBD"
labels: "✎ draft, ☰ story"
assignees: []
body:
  # - type: markdown
  #   attributes:
  #     value: |
        
  - type: textarea
    id: result
    attributes:
      label: What
      description: |
        **Does this product have or affect a background process?**
        _What task(s) or decision(s) does it represent? What do they do- in detail?_
        **Does this product have or affect a frontend user interface?**
        _What are the representing wireframe(s) or doodle(s)?_
      value:
    validations:
      required: true
