name: "☰ New Story"
description: "Add a new product story to this project."
title: "Story: TBD"
labels: "✎ draft, ☰ story"
assignees: []
body:
  - type: textarea
    id: what
    attributes:
      label: What
      description: |
        **_What is the product?_**<br /><br />
        **Does this product have or affect a background process?***<br />
        _What task(s) or decision(s) from the BPMN document does it represent? Describe them and their behaviors in detail._<br />
        **Does this product have or affect a frontend user interface?**<br />
        _Include wireframes or doodles, describe all components usable or visible in the Product._
      value: |
         _To be described_

         ## Notable Features & Behaviors
         - Feature or Behavior 1
         - Feature or Behavior 2
         - Feature or Behavior 3
    validations:
      required: true
  - type: textarea
    id: where
    attributes:
      label: Where
      description: |
        **_Where is the Product among all the others?_**<br /><br />
        **Does this product have or affect a background process?***<br />
        _Which process, or area of the process, is utilized from the BPMN diagram- what functional area or workflow?_<br />
        **Does this product have or affect a frontend user interface?**<br />
        _Which location(s) are utilized from the Site Map?_<br />
      value: |
         _To be described_
    validations:
      required: true
  - type: textarea
    id: who
    attributes:
      label: Who
      description: |
         **_Who is using the Product?_**<br /><br />
         List all automated actors and roles involved, what actions can they take, and any constraints they have with regards to this story.
      value: |
         | Name | Action/Subject | Constraints |
         |-|:-|:-|
         | Actor 1 | TBD | _None_ |
         | Actor 2 | TBD | _None_ |
         | Actor 3 | TBD | _None_ |
  - type: textarea
    id: why
    attributes:
      label: Why
      description: |
         **_Why is this Product valuable?_**<br /><br />
         What is the purpose of this product, what value does it provide to the customer?
      value: |
         _To be described_
