name: "⚙ New Behavior"
description: "Add a new behavior to this project."
title: "New Behavior"
labels: "triage, ⚙ behavior"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > The **title** of this issue will be processed by the AppKu AI. You may include a brief title to help guide the AI or leave it as-is.
        
        # :gear: Welcome!
        This form is filled out to add a new formal Behavior to the project Plan.    
  - type: input
    id: actor
    attributes:
      label: Actor(s)
      description: What types of users (Administrators, readers, etc.) would be able to perform the actions described?
      value: User
    validations:
      required: true
  - type: dropdown
    id: action
    attributes:
      label: Action
      description: What is the action they will perform?
      options:
        - Activates
        - Clicks
        - Deselects
        - Drags
        - Drops
        - Focuses
        - Gestures
        - Grabs
        - Hovers
        - Installs
        - Loads
        - Pinches
        - Presses
        - Resizes
        - Scrolls
        - Selects
        - Swipes
        - Toggles
        - Triggers
        - Types
        - Unfocuses
        - Uninstalls
        - Unloads
    validations:
      required: true
  - type: input
    id: action-subject
    attributes:
      label: "Action: Subject"
      description: What are they affecting with the action (directly), and are there conditions?
      value: 
  - type: input
    id: action-conditions
    attributes:
      label: "Action: Conditions"
      description: Are there special conditions or considerations for the action to be performed?
      value: None
  - type: textarea
    id: result
    attributes:
      label: Results
      description: What is the Result of the Actor(s) performing the Action?
      value:
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: Is there any addition context that should be included about this behavior?
      placeholder: Calculations, samples, considerations, data sources, etc.
      value:
