name: "\U000026AF New Story Ask"
description: "A plan to improve or enhance an existing product."
title: "Ask: [Brief Description]"
labels: 
  - "✎ triage"
  - "⚯ ask"
assignees: []
type: "Ask"
body:
  - type: textarea
    id: ask
    attributes:
      label: Ask
      description: |
        **_What is the ask?_**
      value: 
    validations:
      required: true
  - type: textarea
    id: story-changes
    attributes:
      label: Changes to the Story
      description: |
        **_What, Where, Who, & Why?_**
      value: |
        ##### Changes to _What_
        _None_
        ##### Changes to _Where_
        _None_
        ##### Changes to _Who_
        _None_
        ##### Changes to _Why_
        _None_
